---
name: custommenus
---
Controller:
  extensions:
    - 'CustomMenu'
SiteTree:
  extensions:
    - 'CustomMenuExtension'
LeftAndMain:
  extensions:
    - 'CustomMenu_LeftAndMain'

---
Name: translatablecustommenu
Only:
  ModuleExists: translatable
---
Injector:
  CustomMenu:
    class: TranslatableCustomMenu
