---
name: custommenus
---
Controller:
  extensions:
    - 'CustomMenu'
SiteTree:
  extensions:
    - 'CustomMenuExtension'
SiteConfig:
  extensions:
    - 'CustomMenuSiteConfigExtension'

---
Only:
  moduleexists: 'cms'
---
CustomMenuLink:
  base_classes:
    "SiteTree": "Page on site"
    - 'CustomMenu_LeftAndMain'
---
Only:
  ModuleExists: translatable
---
Injector:
  CustomMenu:
    class: TranslatableCustomMenu