---
name: custommenus
---
SilverStripe\Control\Controller:
  extensions:
    - 'ilateral\SilverStripe\CustomMenus\Extensions\ControllerExtension'
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'ilateral\SilverStripe\CustomMenus\Extensions\CustomMenuExtension'
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'ilateral\SilverStripe\CustomMenus\Extensions\SiteConfigExtension'

---
Only:
  moduleexists: 'silverstripe/cms'
---
ilateral\SilverStripe\CustomMenus\Model\CustomMenuLink:
  base_classes:
    '\SilverStripe\CMS\Model\SiteTree': "Page on site"