<?php

namespace DFT\SilverStripe\CustomMenus\Extensions;

use SilverStripe\Core\Extension;
use SilverStripe\SiteConfig\SiteConfig;
use SilverStripe\Core\Convert;
use DFT\SilverStripe\CustomMenus\Model\CustomMenuHolder;
use DFT\SilverStripe\CustomMenus\Model\CustomMenuList;

class ControllerExtension extends Extension
{

    /**
     * Generate an list of items that will be loaded into the custom menu
     *
     * @param $menu template slug for retriving a menu
     *
     * @return \DFT\SilverStripe\CustomMenus\Model\CustomMenuList
     */
    public function CustomMenu($menu = "")
    {
        $menu_items = CustomMenuList::create();
        $config = SiteConfig::current_site_config();

        if (isset($menu)) {
            // Ensure argument is safe for database
            $menu = Convert::raw2sql($menu);

            $menu_holder = CustomMenuHolder::get()
                ->filter([
                    'SiteID' => $config->ID,
                    'Slug' => $menu
                ])->first();

            if ($menu_holder && $menu_holder->Links()->exists()) {
                $menu_items->setHolder($menu_holder);
                foreach ($menu_holder->Links() as $link) {
                    $object = $link->Object();
                    if ($object->exists()) {
                        $menu_items->add($object);
                    }
                }
            }
        }

        return $menu_items;
    }

    /**
     * Take a list of custom menu items and render it into a
     * template.
     *
     * @param $menu Template slug generated by the CMS
     * @return string
     */
    public function RenderedCustomMenu($menu = "", $show_heading = false)
    {
        $owner = $this->getOwner();

        return $owner
            ->renderWith(
                'DFT\SilverStripe\CustomMenus\Includes\CustomMenu',
                [
                    'Slug' => $menu,
                    'Menu' => $owner->CustomMenu($menu),
                    'ShowHeading' => $show_heading
                ]
            );
    }
}
